name: Autograding Tests
on: [push, pull_request]  # Trigger on push and pull request events
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'  # Skip if triggered by classroom bot
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Check out the repository code
    - name: test_assignment.py
      id: test_assignment-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10  # Timeout for tests (in seconds)
        max-score: 100  # Maximum score for the assignment
        setup-command: pip install numpy pandas pytest  # Install required dependencies
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_ASSIGNMENT-PY_RESULTS: "${{steps.test_assignment-py.outputs.result}}"  # Pass test results
      with:
        runners: test_assignment-py  # Specify the test runner
